# Generated by Django 6.0.6 on 2026-06-08 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('bet_stake', 'Bet Stake'), ('bet_win', 'Bet Win'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('momo', 'Mobile Money'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('crypto', 'Crypto'), ('manual', 'Manual')], default='momo', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=60)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='accounts.accounttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='MyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('GHS', 'Ghana Cedi'), ('NGN', 'Nigerian Naira'), ('KES', 'Kenyan Shilling'), ('USD', 'US Dollar')], default='GHS', max_length=5)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_label', models.CharField(max_length=255)),
                ('market_label', models.CharField(blank=True, default='', max_length=120)),
                ('selection_label', models.CharField(blank=True, default='', max_length=120)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=14)),
                ('odd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('possible_win', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('void', 'Void'), ('cashed_out', 'Cashed Out')], default='open', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='accounts.myaccount')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.myaccount'),
        ),
        migrations.CreateModel(
            name='PayoutSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_type', models.CharField(choices=[('momo', 'Mobile Money'), ('bank', 'Bank Account'), ('crypto', 'Crypto Wallet')], default='momo', max_length=20)),
                ('account_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=80)),
                ('provider_name', models.CharField(blank=True, default='', max_length=120)),
                ('network', models.CharField(blank=True, default='', max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_settings', to='accounts.myaccount')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=80)),
                ('provider', models.CharField(blank=True, default='', max_length=60)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to='accounts.accounttransaction')),
            ],
        ),
    ]
