# Generated by Django 6.0.5 on 2026-06-08 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounttransaction_deposit_myaccount_bethistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_odds', models.DecimalField(decimal_places=4, max_digits=12)),
                ('possible_win', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('void', 'Void'), ('cashed_out', 'Cashed Out')], default='open', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_tickets', to='accounts.myaccount')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='BetLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=120)),
                ('match_label', models.CharField(max_length=255)),
                ('market_label', models.CharField(blank=True, default='', max_length=120)),
                ('selection_label', models.CharField(max_length=120)),
                ('pick_side', models.CharField(blank=True, default='', max_length=16)),
                ('market_key', models.CharField(blank=True, default='', max_length=80)),
                ('odd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='accounts.betticket')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
