# Generated by Django 6.0.5 on 2026-06-10 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myaccount_withdrawal_deposit_count'),
        ('agents', '0001_referral_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='referral_code_used',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='myaccount',
            name='referred_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='agents.referralagent'),
        ),
    ]
