# Generated by Django 6.0.5 on 2026-06-08 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_scripted',
            field=models.BooleanField(default=True, help_text='When enabled, match goes live at kickoff using scripted goals and settles bets at full time.'),
        ),
        migrations.AddField(
            model_name='match',
            name='kicked_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='live_duration_minutes',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='match',
            name='outcome_away_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Final away goals (scripted outcome).', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='outcome_home_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Final home goals (scripted outcome).', null=True),
        ),
        migrations.CreateModel(
            name='MatchGoalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=8)),
                ('match_minute', models.PositiveSmallIntegerField(help_text="Minute shown in live feed, e.g. 23 for 23'.")),
                ('appears_at', models.DateTimeField(help_text='Wall-clock time when this goal is revealed in the live feed.')),
                ('is_applied', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_events', to='app.match')),
            ],
            options={
                'ordering': ['appears_at', 'sort_order', 'id'],
            },
        ),
    ]
